packages:
  - apps/user/*
  - apps/core/*
  - packages/*
  - tooling/*

catalog:
  "@biomejs/biome": ^1.9.4
  "@tsconfig/strictest": ^2.0.5
  "@types/node": ^22.14.0
  "@vitest/coverage-v8": ^3.1.1
  fix-esm-import-path: ^1.10.1
  sort-package-json: ^3.0.0
  ts-node: ^10.9.2
  tsc-alias: ^1.8.13
  tsup: ^8.4.0
  tsx: ^4.19.3
  typescript: ^5.8.3
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.1.1
