direction: right

### Shapes
Noos: {
  User: {
    frontend: FrontEnd

    approuter: {
      shape: queue
      label: "BFF\nAppRouter"
    }
  }

  Core: {
    yoga: {
      shape: queue
      label: "Graph Organizer\nYoga"
    }

    worker: {
      label: "Worker\nNestJS"
    }

    graphdb: {
      shape: cylinder
      label: "GraphDB\nDgraph"
    }

    rdbms: {
      shape: cylinder
      label: "RDBMS\nCockroachDB"
    }

    blob: {
      shape: cylinder
      label: "Blob Storage\nS3-compatible"
    }
  }
}

### Connections
Noos.User.frontend -> Noos.User.approuter: {
  label: "tRPC"
  style: {
    stroke: green
  }
}

Noos.User.frontend -> Noos.Core.yoga: {
  label: "GraphQL"
  style: {
    stroke: red
  }
}

Noos.User.approuter -> Noos.Core.yoga: {
  label: "GraphQL"
  style: {
    stroke: red
  }
}

Noos.User.approuter -> Noos.Core.worker: {
  label: "gRPC"
  style: {
    stroke: blue
  }
}

Noos.User.approuter -> Noos.Core.blob: {}

Noos.Core.yoga -> Noos.Core.graphdb: {
  label: "GraphQL"
  style: {
    stroke: red
  }
}

Noos.Core.yoga -> Noos.Core.blob: {}

Noos.Core.worker -> Noos.Core.rdbms: {}

Noos.Core.worker -> Noos.Core.yoga: {
  label: "GraphQL"
  style: {
    stroke: red
  }
}
